env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - xo
overrides:
  - extends:
      - xo-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: {}
